CREATE DATADATE airline_Matthieu
DROP USER IF EXISTS Matthieu@'%' ;
CREATE USER IF NOT EXISTS Matthieu@'%' IDENTIFIED BY '12112003';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Matthieu.* TO 'Matthieu'@'%';
CREATE DATADATE airline_Victor
DROP USER IF EXISTS Victor@'%' ;
CREATE USER IF NOT EXISTS Victor@'%' IDENTIFIED BY '13092001';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Victor.* TO 'Victor'@'%';
CREATE DATADATE airline_Elowan
DROP USER IF EXISTS Elowan@'%' ;
CREATE USER IF NOT EXISTS Elowan@'%' IDENTIFIED BY '14082004';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Elowan.* TO 'Elowan'@'%';
CREATE DATADATE airline_Corentin
DROP USER IF EXISTS Corentin@'%' ;
CREATE USER IF NOT EXISTS Corentin@'%' IDENTIFIED BY '04082004';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Corentin.* TO 'Corentin'@'%';
CREATE DATADATE airline_Angel
DROP USER IF EXISTS Angel@'%' ;
CREATE USER IF NOT EXISTS Angel@'%' IDENTIFIED BY '28122004';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Angel.* TO 'Angel'@'%';
CREATE DATADATE airline_Lheo
DROP USER IF EXISTS Lheo@'%' ;
CREATE USER IF NOT EXISTS Lheo@'%' IDENTIFIED BY '15122003';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Lheo.* TO 'Lheo'@'%';
CREATE DATADATE airline_Aleksander
DROP USER IF EXISTS Aleksander@'%' ;
CREATE USER IF NOT EXISTS Aleksander@'%' IDENTIFIED BY '04102004';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Aleksander.* TO 'Aleksander'@'%';
CREATE DATADATE airline_Matheo
DROP USER IF EXISTS Matheo@'%' ;
CREATE USER IF NOT EXISTS Matheo@'%' IDENTIFIED BY '17122004';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Matheo.* TO 'Matheo'@'%';
CREATE DATADATE airline_Mathieu
DROP USER IF EXISTS Mathieu@'%' ;
CREATE USER IF NOT EXISTS Mathieu@'%' IDENTIFIED BY '22072003';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Mathieu.* TO 'Mathieu'@'%';
CREATE DATADATE airline_Chloé
DROP USER IF EXISTS Chloé@'%' ;
CREATE USER IF NOT EXISTS Chloé@'%' IDENTIFIED BY '08072004';
GRANT SELECT, INSERT, EXECUTE, ALTER, CREATE, TRIGGER ON airline_Chloé.* TO 'Chloé'@'%';
FLUSH PRIVILEGES;

